DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS ProductTag;

CREATE TABLE Category (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  catagory_name VARCHAR(30) NOT NULL
);

CREATE TABLE Product (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  product_name VARCHAR(30) NOT NULL,
  price DECIMAL NOT NULL,
  stock INTEGER (10) NOT NULL,
  catagory_id INTEGER FOREIGN KEY REFERENCES (Category id),
);

CREATE TABLE Tag (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(30) NOT NULL
);

CREATE TABLE ProductTag (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  product_id VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES(Product id),
  tag_id VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES(Tag id),
);